apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "argocd"
  namespace: "argocd"
spec:
  generators:
    - git:
        repoURL: "https://github.com/conquerproject/conquer-platform.git"
        revision: "main"
        files:
          - path: "argocd/clusters/aks-conquerproject-dev-01.yaml"
  template:
    metadata:
      name: "argocd-{{ clusterName }}"
    spec:
      project: "default"
      sources:
        - repoURL: "https://github.com/conquerproject/conquer-platform.git"
          targetRevision: "{{ revision }}"
          ref: valuesRepo

        - repoURL: "https://argoproj.github.io/argo-helm"
          chart: "argo-cd"
          targetRevision: "6.1"
          helm:
            releaseName: "argocd"
            valueFiles:
              - $valuesRepo/argocd/defaults/argocd/values.yaml

        - repoURL: "https://github.com/conquerproject/conquer-platform.git"
          targetRevision: "{{ revision }}"
          path: argocd/defaults/argocd/manifests
          directory:
            recurse: true

      destination:
        server: "{{ server }}"
        namespace: "argocd"

      syncPolicy:
        automated: {}
