apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "cert-manager"
  namespace: "argocd"
spec:
  generators:
    - git:
        repoURL: "https://github.com/conquerproject/conquer-platform.git"
        revision: "main"
        files:
          - path: "argocd/clusters/aks-conquerproject-dev-01.yaml"
  template:
    metadata:
      name: "cert-manager-{{ clusterName }}"
    spec:
      project: "kube-tools"
      sources:
        - repoURL: "https://github.com/conquerproject/conquer-platform.git"
          targetRevision: "{{ revision }}"
          ref: valuesRepo

        - repoURL: "https://charts.jetstack.io"
          chart: "cert-manager"
          targetRevision: "v1.15"
          helm:
            releaseName: "cert-manager"
            valueFiles:
              - $valuesRepo/argocd/defaults/cert-manager/values.yaml

      destination:
        server: "{{ server }}"
        namespace: "cert-manager"

      syncPolicy:
        automated: {}
        syncOptions:
          - "CreateNamespace=true"
