
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "external-dns"
  namespace: "argocd"
spec:
  generators:
    - git:
        repoURL: "https://github.com/conquerproject/conquer-platform.git"
        revision: "main"
        files:
          - path: "argocd/clusters/aks-conquerproject-dev-01.yaml"
  template:
    metadata:
      name: "external-dns-{{ clusterName }}"
    spec:
      project: "kube-tools"
      sources:
        - repoURL: "https://github.com/conquerproject/conquer-platform.git"
          targetRevision: "{{ revision }}"
          ref: valuesRepo

        - repoURL: "https://kubernetes-sigs.github.io/external-dns"
          chart: "external-dns"
          targetRevision: "1.14.5"
          helm:
            releaseName: "external-dns"
            valueFiles:
              - $valuesRepo/argocd/default-charts-values/external-dns/values.yaml

      destination:
        server: "{{ server }}"
        namespace: "kube-tools"

      syncPolicy:
        automated: {}
        syncOptions:
          - "CreateNamespace=true"
