apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "istio"
  namespace: "argocd"
spec:
  generators:
    - git:
        repoURL: "https://github.com/conquerproject/conquer-platform.git"
        revision: "main"
        files:
          - path: "argocd/clusters/aks-conquerproject-dev-01.yaml"
  template:
    metadata:
      name: "istio-{{ clusterName }}"
    spec:
      project: "kube-tools"
      sources:
        # Install Kubernetes Gateway API CRDs
        - repoURL: "https://github.com/kubernetes-sigs/gateway-api"
          targetRevision: "v1.1.0"
          path: "config/crd/"

        - repoURL: "https://github.com/conquerproject/conquer-platform.git"
          targetRevision: "{{ revision }}"
          ref: valuesRepo

        # Install Istio controller
        - repoURL: "https://istio-release.storage.googleapis.com/charts"
          chart: "istiod"
          targetRevision: "1.23"
          helm:
            releaseName: "istio-control"
            valueFiles:
              - $valuesRepo/argocd/defaults/istio-control/values.yaml

        # Install addicional istio-related Objects. E.g: gateway
        - repoURL: "https://github.com/conquerproject/conquer-platform.git"
          targetRevision: "{{ revision }}"
          path: argocd/defaults/istio-control/manifests/
          directory:
            recurse: true

      destination:
        server: "{{ server }}"
        namespace: "istio-system"

      syncPolicy:
        automated: {}
        syncOptions:
          - "CreateNamespace=true"
