apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "kube-prometheus-stack"
  namespace: "argocd"
spec:
  generators:
    - git:
        repoURL: "https://github.com/conquerproject/conquer-platform.git"
        revision: "main"
        files:
          - path: "argocd/clusters/aks-conquerproject-dev-01.yaml"
  template:
    metadata:
      name: "kube-prometheus-stack-{{ clusterName }}"
    spec:
      project: "kube-tools"
      sources:
        - repoURL: "https://github.com/conquerproject/conquer-platform.git"
          targetRevision: "{{ revision }}"
          ref: valuesRepo

        - repoURL: "https://prometheus-community.github.io/helm-charts"
          chart: "kube-prometheus-stack"
          targetRevision: "62.3"
          helm:
            releaseName: "kube-prometheus-stack"
            valueFiles:
              - $valuesRepo/argocd/defaults/grafana-stack/kube-prometheus-stack/values.yaml

      destination:
        server: "{{ server }}"
        namespace: "kube-tools"

      syncPolicy:
        automated: {}
        syncOptions:
          - "CreateNamespace=true"
