apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/conquerproject/conquer-platform.git"
        revision: "main"
        files:
          - path: "argocd/clusters/aks-conquerproject-dev-eastus-01.yaml"

  template:
    metadata:
      name: sealed-secrets-controller
    spec:
      project: kube-tools
      source:
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        chart: "sealed-secrets"
        targetRevision: "2.15"  # It will apply any patches automatically. The current latest version is 2.15.0.
        helm:
          releaseName: "sealed-secrets"

      destination:
        server: "{{ server }}"
        namespace: "kube-tools"

      syncPolicy:
        automated: {}
        syncOptions:
          - "CreateNamespace=true"
