runtimeConfig:
  overrides:
    default:
      ruler_max_rules_per_rule_group: 50

ingester:
  replicas: 1

ruler_querier:
  replicas: 1

ruler_query_scheduler:
  replicas: 1

querier:
  replicas: 1

query_scheduler:
  replicas: 1
