datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: mimir
      type: prometheus
      url: http://mimir-nginx.kube-tools.svc:80/prometheus
      access: proxy
      isDefault: false
