# This root application will apply all applicationsets under conquerproject/argocd/applicationsets/
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: root
  namespace: argocd

spec:
  project: "default" # keep default for bootstrap
  sources:
    - repoURL: https://github.com/conquerproject/conquer-platform.git
      targetRevision: &revision "main"
      path: argocd/applicationsets
      directory:
        recurse: true
        exclude: '{tools/mimir.yaml,tools/kube-prometheus-stack.yaml,tools/grafana.yaml}'

    - repoURL: https://github.com/conquerproject/conquer-platform.git
      targetRevision: *revision
      path: argocd/projects

  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

  syncPolicy:
    automated: {}
