name: 'Terragrunt'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs: 
  terragrunt:
    uses: conquerproject/reusable-workflows/.github/workflows/terragrunt.yaml@feat/terragrunt-workflow-#2
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
